apiVersion: engine.kubevault.com/v1alpha1
kind: ElasticsearchRole
metadata:
  name: es-quickstart
  namespace: demo
spec:
  vaultRef:
    name: vault
  databaseRef:
    name: es-quickstart
    namespace: demo
  path: "custom-database-path"
  creationStatements:
    - "{ \"db\": \"admin\", \"roles\": [{ \"role\": \"readWrite\" }, {\"role\": \"read\", \"db\": \"foo\"}] }"
  defaultTTL: 1h
  maxTTL: 24h
