apiVersion: engine.kubevault.com/v1alpha1
kind: ElasticsearchRole
metadata:
  name: es-quickstart
  namespace: demo
spec:
  vaultRef:
    name: vault
  databaseRef:
    name: es-quickstart
    namespace: demo
  path: "custom-database-path" 
  creationStatements: 
    - '{"elasticsearch_roles": ["superuser"]}'
  defaultTTL: 1h
  maxTTL: 24h