apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: es-quickstart
  namespace: demo
spec:
  vaultRef:
    name: vault
  elasticsearch:
    databaseRef:
      name: es-quickstart
      namespace: demo
    pluginName: "elasticsearch-database-plugin"
    caCert: "/etc/vault/data/data-0/ca.crt"
    clientCert: "/etc/vault/data/data-0/tls.crt"
    clientKey: "/etc/vault/data/data-0/tls.key"
  path: "custom-database-path"